apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Orange
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: yellow team repo for test backstage
spec:
  type: website
  owner: orange
  lifecycle: production
  providesApis:
  - API2
