apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: Orange
  tags: 
  - java
spec:
  lifecycle: production
  owner: orange
  type: website
  system: backstage
  providesApis:
    - blue-team-api
  consumesApis:
    - red-team-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: blue-team-api
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/backstage-test-kim/red-team-repo
spec:
  type: grpc
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: red-team-api
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: grpc
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
