apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: Orange
  tags:
  - java
spec:
  lifecycle: production
  owner: orange
  providesApis:
  - API1
  system: backstage
  type: website
