apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orange
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: orange
  lifecycle: production
  providesApis:
  - API7
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API7
spec:
  type: grpc
  lifecycle: experimental
  owner: orange
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
