apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: An example of a Backstage application.
  lifecycle: experimental
  name: Orange
  owner: team-a
  type: service
  tags:
  - yaml
spec:
  consumesApis:
  - red-team-api
  lifecycle: production
  owner: orange
  providesApis:
  - blue-team-api
  type: website
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/backstage-test-kim/red-team-repo
  name: blue-team-api
spec:
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
  lifecycle: production
  owner: team-a
  type: grpc
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: red-team-api
spec:
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
  lifecycle: production
  owner: team-a
  type: grpc
