apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: API1
  tags:
  - java
spec:
  lifecycle: experimental
  owner: orange
  type: grpc
  system: backstage
  providesApis:
  - API1
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: API1
  tags:
  - java
spec:
  lifecycle: experimental
  owner: orange
  type: grpc
  system: backstage
  providesApis:
  - API1
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
