apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orange2
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: orange
  lifecycle: production
  providesApis:
  - API1
  dependsOn:
  - "component:name-component"
  - "resource:artists-db"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API1
spec:
  type: grpc
  lifecycle: experimental
  owner: orange
  definition: |
    syntax = "proto3";
    option java_multiple_files = true;
    package helloworld;
    service Greeter {
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: artists-db
  description: Stores artist details
spec:
  type: database
  owner: team-a
  system: artist-engagement-portal
