apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Orange
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage-test-kim/yellow-team-repo
spec:
  type: website
  owner: kim
  lifecycle: production
  providesApis:
  - API2
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API2
spec:
  type: grpc
  lifecycle: experimental
  owner: orange
  definition:
    $text: https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto
