apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Yellow Team
  description: test
  annotations:
    backstage.io/techdocs-ref: dir:.
  tag:
    - java
spec:
  type: service
  owner: yellow
  lifecycle: production
  providesApis:
     - api1
     - api2
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api1
spec:
  type: grpc
  lifecycle: production
  owner: yellow
  definition:
    $text: https://github.com/aystzh/go-modules/blob/master/protobuf/simple_service.proto
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api2
spec:
  type: grpc
  lifecycle: experimental
  owner: yellow
  definition:
    $text: https://github.com/aystzh/go-modules/blob/master/protobuf/simple_service.proto
