name: Create Catalog-info.yaml

on:
  push:
    branches: [main]
    paths:
      - 'catalog-info.yaml'
      - '.github/workflows/backstage-catalog.yaml'

jobs:
  create-backstage-config-file:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.check_changes.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: backstage-test-kim/red-team-repo
          path: red-team-repo
          submodules: 'false'
     
      - id: get_des
        run: |
         data=$(curl \
         -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" \
         ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY} | jq '.description')
         echo "::set-output name=description::$data"
      - id: get_tag
        run: |
         TAG=$(curl \
         -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.mercy-preview+json" \
         ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/topics | jq -r '.names[]? | join(",")')
         echo "::set-output name=tag::$TAG"
           
      - name: generate catalog-info.yaml
        uses: kim5566/catalog-generate-action@main
        with:
          config_file: '{"Name":"Orange","Team":"orange","Lifecycle":"production","Type":"website","ProvidesApis":[{"Name":"API2", "Type":"grpc","Lifecycle":"experimental","Definition":"https://github.com/backstage-test-kim/test-action-mkdocs/blob/master/test.proto"}]}'
          description: ${{ steps.get_des.outputs.description }}
          topic: ${{ steps.get_tag.outputs.tag }}
          
      - run: cat catalog-info.yaml


      - run: echo ${GITHUB_REPOSITORY}
    
      - name: Check diff
        shell: bash
        run: |
          rm -rf red-team-repo
          if [ -z "$(git diff --exit-code)" -a -z "$(git ls-files -o --exclude-standard)" ]
          then
            echo "nothing to commit. skip pr"
            touch skip-pr
          else
            echo "catalog-info.yaml" updated
            git add catalog-info.yaml
          fi
          
      - name: Create Pull Request
        if: hashFiles('skip-pr') == ''
        uses: peter-evans/create-pull-request@v3
        with:
          title: Auto-update Backstage catalog-info.yaml configuration
          commit-message: 'auto-update Backstage catalog-info.yaml configuration'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            # Origin Details
            **Message**: ${{ github.event.head_commit.message }}
          branch: feature/update-backstage
          labels: |
             backstage
             autogenerated

